name: Build tests

# we using a matrix testing https://github.com/actions/setup-dotnet

on: [push]

jobs:
  build:

    runs-on: windows-latest
    name: Dotnet Side by Side testing sample

    steps:
    - name: ğŸ› Checkout repo
      uses: actions/checkout@v2
    - name: ğŸš§ Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: ğŸš§ Setup .NET core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '3.1'
    - name: ğŸš§ Setup standard
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '2.1'
    # install dependecies will be used when we will have dependencies    
    - name: âš™ï¸ Install dependencies
      run: dotnet add src/GShark/GShark.csproj package Newtonsoft.Json --version 13.0.1
    - name: ğŸ— Build
      run: dotnet build src/GShark/GShark.csproj --configuration Release --no-restore
    - name: ğŸ§ª Test
      run: dotnet test src/GShark/GShark.csproj --no-restore
